on:
  push:
    branches: ["main"]

name: Build and deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Zola
        uses: Deuchnord/zola-deploy-action@fix/safe-directory
        env:
          PAGES_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
